CREATE TABLE CUSTOMER_REWARDS (
    REWARD_ID NUMBER GENERATED AS IDENTITY (START WITH 101 INCREMENT BY 1) PRIMARY KEY,
    CUSTOMER_EMAIL VARCHAR2(255) NOT NULL,
    GIFT_ID NUMBER NOT NULL,
    REWARD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cr_gift FOREIGN KEY (GIFT_ID) REFERENCES GIFT_CATALOG(GIFT_ID),
    CONSTRAINT fk_cr_customer_email FOREIGN KEY (CUSTOMER_EMAIL) REFERENCES CUSTOMERS(email_address)
);

COMMIT;